# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stocks.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cstocks.proto\";\n\x0crequestStock\x12\r\n\x05\x63\x63ode\x18\x01 \x01(\t\x12\x1c\n\x04\x64\x61te\x18\x02 \x01(\x0e\x32\x0e.DateCategory2\"+\n\x0brequestDate\x12\x1c\n\x04\x64\x61te\x18\x01 \x01(\x0e\x32\x0e.DateCategory2\"2\n\nprice_hist\x12\x16\n\x0ehistoric_price\x18\x01 \x01(\x02\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\"\x8a\x01\n\rresponseStock\x12\r\n\x05price\x18\x01 \x01(\x02\x12\x15\n\raverage_price\x18\x02 \x01(\x02\x12\r\n\x05\x63\x63ode\x18\x03 \x01(\t\x12\x11\n\tmax_price\x18\x04 \x01(\x02\x12\x11\n\tmin_price\x18\x05 \x01(\x02\x12\x1e\n\tprice_Arr\x18\x06 \x03(\x0b\x32\x0b.price_hist\"d\n\x08infoDate\x12\r\n\x05\x63\x63ode\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\x12\x15\n\rcurrent_price\x18\x03 \x01(\x02\x12\x11\n\tmax_price\x18\x04 \x01(\x02\x12\x11\n\tmin_price\x18\x05 \x01(\x02\"/\n\x0cresponseDate\x12\x1f\n\x0cstockDateArr\x18\x01 \x03(\x0b\x32\t.infoDate*C\n\rDateCategory2\x12\n\n\x06\x64\x61ily_\x10\x00\x12\x0b\n\x07weekly_\x10\x01\x12\x0c\n\x08monthly_\x10\x02\x12\x0b\n\x07yearly_\x10\x03\x32i\n\x06Stocks\x12\x31\n\x10getStocksCompany\x12\r.requestStock\x1a\x0e.responseStock\x12,\n\rgetStocksDate\x12\x0c.requestDate\x1a\r.responseDateb\x06proto3')

_DATECATEGORY2 = DESCRIPTOR.enum_types_by_name['DateCategory2']
DateCategory2 = enum_type_wrapper.EnumTypeWrapper(_DATECATEGORY2)
daily_ = 0
weekly_ = 1
monthly_ = 2
yearly_ = 3


_REQUESTSTOCK = DESCRIPTOR.message_types_by_name['requestStock']
_REQUESTDATE = DESCRIPTOR.message_types_by_name['requestDate']
_PRICE_HIST = DESCRIPTOR.message_types_by_name['price_hist']
_RESPONSESTOCK = DESCRIPTOR.message_types_by_name['responseStock']
_INFODATE = DESCRIPTOR.message_types_by_name['infoDate']
_RESPONSEDATE = DESCRIPTOR.message_types_by_name['responseDate']
requestStock = _reflection.GeneratedProtocolMessageType('requestStock', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTSTOCK,
  '__module__' : 'stocks_pb2'
  # @@protoc_insertion_point(class_scope:requestStock)
  })
_sym_db.RegisterMessage(requestStock)

requestDate = _reflection.GeneratedProtocolMessageType('requestDate', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTDATE,
  '__module__' : 'stocks_pb2'
  # @@protoc_insertion_point(class_scope:requestDate)
  })
_sym_db.RegisterMessage(requestDate)

price_hist = _reflection.GeneratedProtocolMessageType('price_hist', (_message.Message,), {
  'DESCRIPTOR' : _PRICE_HIST,
  '__module__' : 'stocks_pb2'
  # @@protoc_insertion_point(class_scope:price_hist)
  })
_sym_db.RegisterMessage(price_hist)

responseStock = _reflection.GeneratedProtocolMessageType('responseStock', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSESTOCK,
  '__module__' : 'stocks_pb2'
  # @@protoc_insertion_point(class_scope:responseStock)
  })
_sym_db.RegisterMessage(responseStock)

infoDate = _reflection.GeneratedProtocolMessageType('infoDate', (_message.Message,), {
  'DESCRIPTOR' : _INFODATE,
  '__module__' : 'stocks_pb2'
  # @@protoc_insertion_point(class_scope:infoDate)
  })
_sym_db.RegisterMessage(infoDate)

responseDate = _reflection.GeneratedProtocolMessageType('responseDate', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEDATE,
  '__module__' : 'stocks_pb2'
  # @@protoc_insertion_point(class_scope:responseDate)
  })
_sym_db.RegisterMessage(responseDate)

_STOCKS = DESCRIPTOR.services_by_name['Stocks']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DATECATEGORY2._serialized_start=466
  _DATECATEGORY2._serialized_end=533
  _REQUESTSTOCK._serialized_start=16
  _REQUESTSTOCK._serialized_end=75
  _REQUESTDATE._serialized_start=77
  _REQUESTDATE._serialized_end=120
  _PRICE_HIST._serialized_start=122
  _PRICE_HIST._serialized_end=172
  _RESPONSESTOCK._serialized_start=175
  _RESPONSESTOCK._serialized_end=313
  _INFODATE._serialized_start=315
  _INFODATE._serialized_end=415
  _RESPONSEDATE._serialized_start=417
  _RESPONSEDATE._serialized_end=464
  _STOCKS._serialized_start=535
  _STOCKS._serialized_end=640
# @@protoc_insertion_point(module_scope)
