# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import stocks_pb2 as stocks__pb2


class StocksStub(object):
    """Service 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getStocksCompany = channel.unary_unary(
                '/Stocks/getStocksCompany',
                request_serializer=stocks__pb2.requestStock.SerializeToString,
                response_deserializer=stocks__pb2.responseStock.FromString,
                )
        self.getStocksDate = channel.unary_unary(
                '/Stocks/getStocksDate',
                request_serializer=stocks__pb2.requestDate.SerializeToString,
                response_deserializer=stocks__pb2.responseDate.FromString,
                )


class StocksServicer(object):
    """Service 
    """

    def getStocksCompany(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getStocksDate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StocksServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getStocksCompany': grpc.unary_unary_rpc_method_handler(
                    servicer.getStocksCompany,
                    request_deserializer=stocks__pb2.requestStock.FromString,
                    response_serializer=stocks__pb2.responseStock.SerializeToString,
            ),
            'getStocksDate': grpc.unary_unary_rpc_method_handler(
                    servicer.getStocksDate,
                    request_deserializer=stocks__pb2.requestDate.FromString,
                    response_serializer=stocks__pb2.responseDate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Stocks', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Stocks(object):
    """Service 
    """

    @staticmethod
    def getStocksCompany(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Stocks/getStocksCompany',
            stocks__pb2.requestStock.SerializeToString,
            stocks__pb2.responseStock.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getStocksDate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Stocks/getStocksDate',
            stocks__pb2.requestDate.SerializeToString,
            stocks__pb2.responseDate.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
