# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\raccount.proto\"8\n\x05Votes\x12\r\n\x05\x63\x63ode\x18\x01 \x01(\t\x12 \n\tvote_type\x18\x02 \x01(\x0e\x32\r.VoteCategory\"4\n\x0egetUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"j\n\x11\x43reateUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x12\n\nbirth_date\x18\x04 \x01(\t\x12\x0e\n\x06gender\x18\x05 \x01(\t\"j\n\x11UpdateUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x12\n\nbirth_date\x18\x04 \x01(\t\x12\x0e\n\x06gender\x18\x05 \x01(\t\"\\\n\x16UpdateUserRequestFinal\x12\x18\n\x10\x64\x65\x66\x61ult_username\x18\x01 \x01(\t\x12(\n\x0c\x62ody_request\x18\x02 \x01(\x0b\x32\x12.UpdateUserRequest\"%\n\x11\x64\x65leteUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"B\n\x0fVoteUserRequest\x12\r\n\x05\x63\x63ode\x18\x01 \x01(\t\x12 \n\tvote_type\x18\x02 \x01(\x0e\x32\r.VoteCategory\"\x1f\n\x0cresponseUser\x12\x0f\n\x07message\x18\x01 \x01(\t\"p\n\x0brespGetUser\x12\x10\n\x08username\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x12\n\nbirth_date\x18\x03 \x01(\t\x12\x0e\n\x06gender\x18\x04 \x01(\t\x12\x1c\n\x0cvote_history\x18\x05 \x03(\x0b\x32\x06.Votes**\n\x0cVoteCategory\x12\x08\n\x04NONE\x10\x00\x12\x06\n\x02Up\x10\x01\x12\x08\n\x04\x44own\x10\x02*>\n\x0c\x44\x61teCategory\x12\t\n\x05\x64\x61ily\x10\x00\x12\n\n\x06weekly\x10\x01\x12\x0b\n\x07monthly\x10\x02\x12\n\n\x06yearly\x10\x03\x32\xfb\x01\n\x07\x41\x63\x63ount\x12)\n\x08readUser\x12\x0f.getUserRequest\x1a\x0c.respGetUser\x12/\n\ncreateUser\x12\x12.CreateUserRequest\x1a\r.responseUser\x12\x34\n\nupdateUser\x12\x17.UpdateUserRequestFinal\x1a\r.responseUser\x12/\n\ndeleteUser\x12\x12.deleteUserRequest\x1a\r.responseUser\x12-\n\ncreateVote\x12\x10.VoteUserRequest\x1a\r.responseUserb\x06proto3')

_VOTECATEGORY = DESCRIPTOR.enum_types_by_name['VoteCategory']
VoteCategory = enum_type_wrapper.EnumTypeWrapper(_VOTECATEGORY)
_DATECATEGORY = DESCRIPTOR.enum_types_by_name['DateCategory']
DateCategory = enum_type_wrapper.EnumTypeWrapper(_DATECATEGORY)
NONE = 0
Up = 1
Down = 2
daily = 0
weekly = 1
monthly = 2
yearly = 3


_VOTES = DESCRIPTOR.message_types_by_name['Votes']
_GETUSERREQUEST = DESCRIPTOR.message_types_by_name['getUserRequest']
_CREATEUSERREQUEST = DESCRIPTOR.message_types_by_name['CreateUserRequest']
_UPDATEUSERREQUEST = DESCRIPTOR.message_types_by_name['UpdateUserRequest']
_UPDATEUSERREQUESTFINAL = DESCRIPTOR.message_types_by_name['UpdateUserRequestFinal']
_DELETEUSERREQUEST = DESCRIPTOR.message_types_by_name['deleteUserRequest']
_VOTEUSERREQUEST = DESCRIPTOR.message_types_by_name['VoteUserRequest']
_RESPONSEUSER = DESCRIPTOR.message_types_by_name['responseUser']
_RESPGETUSER = DESCRIPTOR.message_types_by_name['respGetUser']
Votes = _reflection.GeneratedProtocolMessageType('Votes', (_message.Message,), {
  'DESCRIPTOR' : _VOTES,
  '__module__' : 'account_pb2'
  # @@protoc_insertion_point(class_scope:Votes)
  })
_sym_db.RegisterMessage(Votes)

getUserRequest = _reflection.GeneratedProtocolMessageType('getUserRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETUSERREQUEST,
  '__module__' : 'account_pb2'
  # @@protoc_insertion_point(class_scope:getUserRequest)
  })
_sym_db.RegisterMessage(getUserRequest)

CreateUserRequest = _reflection.GeneratedProtocolMessageType('CreateUserRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEUSERREQUEST,
  '__module__' : 'account_pb2'
  # @@protoc_insertion_point(class_scope:CreateUserRequest)
  })
_sym_db.RegisterMessage(CreateUserRequest)

UpdateUserRequest = _reflection.GeneratedProtocolMessageType('UpdateUserRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEUSERREQUEST,
  '__module__' : 'account_pb2'
  # @@protoc_insertion_point(class_scope:UpdateUserRequest)
  })
_sym_db.RegisterMessage(UpdateUserRequest)

UpdateUserRequestFinal = _reflection.GeneratedProtocolMessageType('UpdateUserRequestFinal', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEUSERREQUESTFINAL,
  '__module__' : 'account_pb2'
  # @@protoc_insertion_point(class_scope:UpdateUserRequestFinal)
  })
_sym_db.RegisterMessage(UpdateUserRequestFinal)

deleteUserRequest = _reflection.GeneratedProtocolMessageType('deleteUserRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETEUSERREQUEST,
  '__module__' : 'account_pb2'
  # @@protoc_insertion_point(class_scope:deleteUserRequest)
  })
_sym_db.RegisterMessage(deleteUserRequest)

VoteUserRequest = _reflection.GeneratedProtocolMessageType('VoteUserRequest', (_message.Message,), {
  'DESCRIPTOR' : _VOTEUSERREQUEST,
  '__module__' : 'account_pb2'
  # @@protoc_insertion_point(class_scope:VoteUserRequest)
  })
_sym_db.RegisterMessage(VoteUserRequest)

responseUser = _reflection.GeneratedProtocolMessageType('responseUser', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEUSER,
  '__module__' : 'account_pb2'
  # @@protoc_insertion_point(class_scope:responseUser)
  })
_sym_db.RegisterMessage(responseUser)

respGetUser = _reflection.GeneratedProtocolMessageType('respGetUser', (_message.Message,), {
  'DESCRIPTOR' : _RESPGETUSER,
  '__module__' : 'account_pb2'
  # @@protoc_insertion_point(class_scope:respGetUser)
  })
_sym_db.RegisterMessage(respGetUser)

_ACCOUNT = DESCRIPTOR.services_by_name['Account']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VOTECATEGORY._serialized_start=693
  _VOTECATEGORY._serialized_end=735
  _DATECATEGORY._serialized_start=737
  _DATECATEGORY._serialized_end=799
  _VOTES._serialized_start=17
  _VOTES._serialized_end=73
  _GETUSERREQUEST._serialized_start=75
  _GETUSERREQUEST._serialized_end=127
  _CREATEUSERREQUEST._serialized_start=129
  _CREATEUSERREQUEST._serialized_end=235
  _UPDATEUSERREQUEST._serialized_start=237
  _UPDATEUSERREQUEST._serialized_end=343
  _UPDATEUSERREQUESTFINAL._serialized_start=345
  _UPDATEUSERREQUESTFINAL._serialized_end=437
  _DELETEUSERREQUEST._serialized_start=439
  _DELETEUSERREQUEST._serialized_end=476
  _VOTEUSERREQUEST._serialized_start=478
  _VOTEUSERREQUEST._serialized_end=544
  _RESPONSEUSER._serialized_start=546
  _RESPONSEUSER._serialized_end=577
  _RESPGETUSER._serialized_start=579
  _RESPGETUSER._serialized_end=691
  _ACCOUNT._serialized_start=802
  _ACCOUNT._serialized_end=1053
# @@protoc_insertion_point(module_scope)
