# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

#import account_pb2 as account__pb2
import account_pb2 as account__pb2

class AccountStub(object):
    """Service 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.readUser = channel.unary_unary(
                '/Account/readUser',
                request_serializer=account__pb2.getUserRequest.SerializeToString,
                response_deserializer=account__pb2.respGetUser.FromString,
                )
        self.createUser = channel.unary_unary(
                '/Account/createUser',
                request_serializer=account__pb2.CreateUserRequest.SerializeToString,
                response_deserializer=account__pb2.responseUser.FromString,
                )
        self.updateUser = channel.unary_unary(
                '/Account/updateUser',
                request_serializer=account__pb2.UpdateUserRequestFinal.SerializeToString,
                response_deserializer=account__pb2.responseUser.FromString,
                )
        self.deleteUser = channel.unary_unary(
                '/Account/deleteUser',
                request_serializer=account__pb2.deleteUserRequest.SerializeToString,
                response_deserializer=account__pb2.responseUser.FromString,
                )
        self.createVote = channel.unary_unary(
                '/Account/createVote',
                request_serializer=account__pb2.VoteUserRequest.SerializeToString,
                response_deserializer=account__pb2.responseUser.FromString,
                )


class AccountServicer(object):
    """Service 
    """

    def readUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def createUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def updateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deleteUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def createVote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AccountServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'readUser': grpc.unary_unary_rpc_method_handler(
                    servicer.readUser,
                    request_deserializer=account__pb2.getUserRequest.FromString,
                    response_serializer=account__pb2.respGetUser.SerializeToString,
            ),
            'createUser': grpc.unary_unary_rpc_method_handler(
                    servicer.createUser,
                    request_deserializer=account__pb2.CreateUserRequest.FromString,
                    response_serializer=account__pb2.responseUser.SerializeToString,
            ),
            'updateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.updateUser,
                    request_deserializer=account__pb2.UpdateUserRequestFinal.FromString,
                    response_serializer=account__pb2.responseUser.SerializeToString,
            ),
            'deleteUser': grpc.unary_unary_rpc_method_handler(
                    servicer.deleteUser,
                    request_deserializer=account__pb2.deleteUserRequest.FromString,
                    response_serializer=account__pb2.responseUser.SerializeToString,
            ),
            'createVote': grpc.unary_unary_rpc_method_handler(
                    servicer.createVote,
                    request_deserializer=account__pb2.VoteUserRequest.FromString,
                    response_serializer=account__pb2.responseUser.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Account', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Account(object):
    """Service 
    """

    @staticmethod
    def readUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Account/readUser',
            account__pb2.getUserRequest.SerializeToString,
            account__pb2.respGetUser.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def createUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Account/createUser',
            account__pb2.CreateUserRequest.SerializeToString,
            account__pb2.responseUser.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def updateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Account/updateUser',
            account__pb2.UpdateUserRequestFinal.SerializeToString,
            account__pb2.responseUser.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def deleteUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Account/deleteUser',
            account__pb2.deleteUserRequest.SerializeToString,
            account__pb2.responseUser.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def createVote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Account/createVote',
            account__pb2.VoteUserRequest.SerializeToString,
            account__pb2.responseUser.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
